const tags = {
	count: 458,
	results: [
		{
			display_name: "North American",
			type: "cuisine",
			root_tag_type: "cuisine",
			id: 64444,
			name: "north_american",
		},
		{
			name: "french",
			display_name: "French",
			type: "european",
			root_tag_type: "cuisine",
			id: 64449,
		},
		{
			display_name: "Japanese",
			type: "asian",
			root_tag_type: "cuisine",
			id: 64454,
			name: "japanese",
		},
		{
			id: 64460,
			name: "thai",
			display_name: "Thai",
			type: "asian",
			root_tag_type: "cuisine",
		},
		{
			type: "dietary",
			root_tag_type: "dietary",
			id: 64465,
			name: "gluten_free",
			display_name: "Gluten-Free",
		},
		{
			name: "low_carb",
			display_name: "Low-Carb",
			type: "healthy",
			root_tag_type: "healthy",
			id: 64467,
		},
		{
			root_tag_type: "dietary",
			id: 64469,
			name: "vegetarian",
			display_name: "Vegetarian",
			type: "dietary",
		},
		{
			id: 64473,
			name: "christmas",
			display_name: "Christmas",
			type: "holidays",
			root_tag_type: "seasonal",
		},
		{
			id: 64474,
			name: "easter",
			display_name: "Easter",
			type: "holidays",
			root_tag_type: "seasonal",
		},
		{
			id: 64480,
			name: "valentines_day",
			display_name: "Valentine's Day",
			type: "holidays",
			root_tag_type: "seasonal",
		},
		{
			id: 64481,
			name: "appetizers",
			display_name: "Appetizers",
			type: "meal",
			root_tag_type: "meal",
		},
		{
			id: 64500,
			name: "date_night",
			display_name: "Date Night",
			type: "occasion",
			root_tag_type: "seasonal",
		},
		{
			id: 64501,
			name: "game_day",
			display_name: "Game Day",
			type: "occasion",
			root_tag_type: "seasonal",
		},
		{
			id: 64505,
			name: "weeknight",
			display_name: "Weeknight",
			type: "dinner",
			root_tag_type: "meal",
		},
		{
			display_name: "Cast Iron Pan",
			type: "appliance",
			root_tag_type: "appliance",
			id: 65840,
			name: "cast_iron_pan",
		},
		{
			type: "cooking_style",
			root_tag_type: "cooking_style",
			id: 65851,
			name: "big_batch",
			display_name: "Big Batch",
		},
		{
			type: "equipment",
			root_tag_type: "equipment",
			id: 1247771,
			name: "cupcake_pan",
			display_name: "Cupcake Pan",
		},
		{
			id: 1247773,
			name: "ice_cube_tray",
			display_name: "Ice Cube Tray",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			name: "paper_cups",
			display_name: "Paper Cups",
			type: "equipment",
			root_tag_type: "equipment",
			id: 1247777,
		},
		{
			id: 1247778,
			name: "paper_napkins",
			display_name: "Paper Napkins",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			name: "parchment_paper",
			display_name: "Parchment Paper",
			type: "equipment",
			root_tag_type: "equipment",
			id: 1247780,
		},
		{
			id: 1247783,
			name: "plastic_utensils",
			display_name: "Plastic Utensils",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			id: 1247785,
			name: "pyrex",
			display_name: "Pyrex",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			id: 1280497,
			name: "baking_kit",
			display_name: "Baking Kit",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 1280505,
			name: "kitchen_shears",
			display_name: "Kitchen Shears",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			type: "equipment",
			root_tag_type: "equipment",
			id: 1280509,
			name: "microplane",
			display_name: "Microplane",
		},
		{
			type: "equipment",
			root_tag_type: "equipment",
			id: 1280514,
			name: "spider",
			display_name: "Spider",
		},
		{
			id: 2651754,
			name: "one_top_app_eggs",
			display_name: "Eggs",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 3956652,
			name: "schwartz_seasoned_pro",
			display_name: "Schwartz Seasoned Pro",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			display_name: "Sponsored Recipe",
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 4202175,
			name: "sponsored_recipe",
		},
		{
			id: 5285641,
			name: "contains_alcohol",
			display_name: "Contains Alcohol",
			type: "dietary",
			root_tag_type: "dietary",
		},
		{
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 5831534,
			name: "best_of_tasty",
			display_name: "Best of Tasty",
		},
		{
			name: "every_occasion",
			display_name: "Every Occasion",
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 6143339,
		},
		{
			id: 6337137,
			name: "holiday_treats",
			display_name: "Holiday Treats",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 6361774,
			name: "for_real_grapefruit",
			display_name: "For Real Grapefruit",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 6389772,
			name: "tasty_holiday_christmas",
			display_name: "Tasty Holiday: Christmas",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 6389774,
			name: "tasty_holiday_nye",
			display_name: "Tasty Holiday: NYE",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6477316,
			name: "frank_s_chicken_bites",
			display_name: "Frank's Chicken Bites",
		},
		{
			root_tag_type: "feature_page",
			id: 6477317,
			name: "frank_s_cheesy_apps",
			display_name: "Frank's Cheesy Apps",
			type: "feature_page",
		},
		{
			id: 6543461,
			name: "nynm_veggie",
			display_name: "NYNM Veggie",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			name: "nynm_instant_pot",
			display_name: "NYNM Instant Pot",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6543463,
		},
		{
			display_name: "MC Breakfast Sweet",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6683350,
			name: "mc_breakfast_sweet",
		},
		{
			name: "mc_breakfast_savory",
			display_name: "MC Breakfast Savory",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6683351,
		},
		{
			display_name: "MC Breakfast Easy",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6683353,
			name: "mc_breakfast_easy",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6807663,
			name: "tasty_ewd_comfort",
			display_name: "Tasty EWD Comfort",
		},
		{
			display_name: "Budget Expert",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6830250,
			name: "budget_expert",
		},
		{
			root_tag_type: "cuisine",
			id: 6953039,
			name: "taiwanese",
			display_name: "Taiwanese",
			type: "asian",
		},
		{
			id: 6953040,
			name: "swedish",
			display_name: "Swedish",
			type: "european",
			root_tag_type: "cuisine",
		},
		{
			type: "cuisine",
			root_tag_type: "cuisine",
			id: 6953045,
			name: "indigenous",
			display_name: "Indigenous",
		},
		{
			name: "mccormick_ugc_one_pot_others",
			display_name: "McCormick UGC One Pot Others",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6986107,
		},
		{
			id: 7041324,
			name: "summer_desserts",
			display_name: "Summer Desserts",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 7145248,
			name: "latinx_heritage_month",
			display_name: "Latinx Heritage Month",
			type: "holiday",
			root_tag_type: "holiday",
		},
		{
			root_tag_type: "feature_page",
			id: 7510773,
			name: "thanksgiving_vegetarian",
			display_name: "Thanksgiving Vegetarian",
			type: "feature_page",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7510780,
			name: "thanksgiving_slow",
			display_name: "Thanksgiving Slow",
		},
		{
			name: "franks_dips",
			display_name: "Franks Dips",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7723150,
		},
		{
			id: 7723151,
			name: "franks_handheld_bites",
			display_name: "Franks Handheld Bites",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 7783332,
			name: "butterfinger_runner_up_cookies",
			display_name: "Butterfinger Runner Up Cookies",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			name: "keto",
			display_name: "Keto",
			type: "dietary",
			root_tag_type: "dietary",
			id: 8091756,
		},
		{
			type: "healthy",
			root_tag_type: "healthy",
			id: 8091918,
			name: "low_sugar",
			display_name: "Low-Sugar",
		},
		{
			name: "rainbow",
			display_name: "Rainbow",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 8322948,
		},
		{
			root_tag_type: "feature_page",
			id: 8600868,
			name: "dole_easy_appetizers",
			display_name: "Dole Easy Appetizers",
			type: "feature_page",
		},
		{
			id: 8683064,
			name: "mccormick_holiday_mains",
			display_name: "McCormick Holiday Mains",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			display_name: "McCormick Holiday Desserts",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 8683065,
			name: "mccormick_holiday_desserts",
		},
		{
			name: "dole_beverages",
			display_name: "Dole Beverages",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 8719452,
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 8874991,
			name: "ethiopia_african_cuisine",
			display_name: "Ethiopia African Cuisine",
		},
		{
			id: 8875006,
			name: "haiti_african_cuisine",
			display_name: "Haiti African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			display_name: "Trinidad African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 8875007,
			name: "trinidad_african_cuisine",
		},
		{
			id: 8875008,
			name: "cuba_african_cuisine",
			display_name: "Cuba African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			display_name: "West Africa African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 8875015,
			name: "west_africa_african_cuisine",
		},
		{
			id: 9104327,
			name: "country_crock_brunch",
			display_name: "Country Crock Brunch",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			display_name: "Country Crock Apps",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 9104328,
			name: "country_crock_apps",
		},
		{
			id: 9299134,
			name: "occasion",
			display_name: "Occasion",
			type: "seasonal",
			root_tag_type: "seasonal",
		},
		{
			id: 9299304,
			name: "polish",
			display_name: "Polish",
			type: "european",
			root_tag_type: "cuisine",
		},
		{
			id: 9299372,
			name: "coffee",
			display_name: "Coffee",
			type: "drinks",
			root_tag_type: "meal",
		},
		{
			display_name: "Pasta",
			type: "dinner",
			root_tag_type: "meal",
			id: 9299522,
			name: "pasta",
		},
		{
			name: "soups",
			display_name: "Soups",
			type: "dinner",
			root_tag_type: "meal",
			id: 9299526,
		},
		{
			root_tag_type: "meal",
			id: 9299529,
			name: "tacos_burritos",
			display_name: "Tacos & Burritos",
			type: "dinner",
		},
		{
			id: 9299794,
			name: "vodka",
			display_name: "Vodka",
			type: "cocktails",
			root_tag_type: "meal",
		},
		{
			display_name: "Whiskey",
			type: "cocktails",
			root_tag_type: "meal",
			id: 9299795,
			name: "whiskey",
		},
		{
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 9835360,
			name: "bushs_meal_planning",
			display_name: "Bush's Meal Planning",
		},
		{
			id: 9835858,
			name: "walmart_meal_planning_july",
			display_name: "Walmart Meal Planning July",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 64452,
			name: "indian",
			display_name: "Indian",
			type: "asian",
			root_tag_type: "cuisine",
		},
		{
			type: "dinner",
			root_tag_type: "meal",
			id: 64459,
			name: "seafood",
			display_name: "Seafood",
		},
		{
			id: 64461,
			name: "vietnamese",
			display_name: "Vietnamese",
			type: "asian",
			root_tag_type: "cuisine",
		},
		{
			display_name: "Comfort Food",
			type: "cooking_style",
			root_tag_type: "cooking_style",
			id: 64462,
			name: "comfort_food",
		},
		{
			id: 64470,
			name: "5_ingredients_or_less",
			display_name: "5 Ingredients or Less",
			type: "difficulty",
			root_tag_type: "difficulty",
		},
		{
			id: 64483,
			name: "breakfast",
			display_name: "Breakfast",
			type: "meal",
			root_tag_type: "meal",
		},
		{
			id: 64488,
			name: "kid_friendly",
			display_name: "Kid-Friendly",
			type: "cooking_style",
			root_tag_type: "cooking_style",
		},
		{
			root_tag_type: "cooking_style",
			id: 64493,
			name: "deep_fry",
			display_name: "Deep-Fry",
			type: "cooking_style",
		},
		{
			id: 64504,
			name: "bbq",
			display_name: "BBQ",
			type: "occasion",
			root_tag_type: "seasonal",
		},
		{
			id: 65844,
			name: "hand_mixer",
			display_name: "Hand Mixer",
			type: "appliance",
			root_tag_type: "appliance",
		},
		{
			name: "wok",
			display_name: "Wok",
			type: "appliance",
			root_tag_type: "appliance",
			id: 65849,
		},
		{
			type: "occasion",
			root_tag_type: "occasion",
			id: 65850,
			name: "indulgent_sweets",
			display_name: "Indulgent Sweets",
		},
		{
			id: 65853,
			name: "meal_prep",
			display_name: "Meal Prep",
			type: "cooking_style",
			root_tag_type: "cooking_style",
		},
		{
			id: 65854,
			name: "no_bake_desserts",
			display_name: "No Bake Desserts",
			type: "cooking_style",
			root_tag_type: "cooking_style",
		},
		{
			id: 65855,
			name: "one_pot_or_pan",
			display_name: "One-Pot or Pan",
			type: "cooking_style",
			root_tag_type: "cooking_style",
		},
		{
			type: "appliance",
			root_tag_type: "appliance",
			id: 65857,
			name: "bakery_goods",
			display_name: "Bakery Goods",
		},
		{
			type: "occasion",
			root_tag_type: "seasonal",
			id: 188967,
			name: "special_occasion",
			display_name: "Special Occasion",
		},
		{
			id: 1036859,
			name: "licensed_video",
			display_name: "Licensed Video",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 1247767,
			name: "bread_pan",
			display_name: "Bread Pan",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			id: 1247779,
			name: "paper_plates",
			display_name: "Paper Plates",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			id: 1247790,
			name: "tongs",
			display_name: "Tongs",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			id: 1247796,
			name: "zipper_storage_bags",
			display_name: "Zipper Storage Bags",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			id: 1280498,
			name: "cooking_kit",
			display_name: "Cooking Kit",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 1280501,
			name: "chefs_knife",
			display_name: "Chef's Knife",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			id: 1280502,
			name: "cooling_rack",
			display_name: "Cooling Rack",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			name: "mixing_bowl",
			display_name: "Mixing Bowl",
			type: "equipment",
			root_tag_type: "equipment",
			id: 1280510,
		},
		{
			type: "equipment",
			root_tag_type: "equipment",
			id: 1280512,
			name: "rolling_pin",
			display_name: "Rolling Pin",
		},
		{
			display_name: "Sieve",
			type: "equipment",
			root_tag_type: "equipment",
			id: 1280513,
			name: "sieve",
		},
		{
			name: "epoca_walmart",
			display_name: "Epoca-Walmart",
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 1691104,
		},
		{
			type: "cuisine",
			root_tag_type: "cuisine",
			id: 3801553,
			name: "african",
			display_name: "African",
		},
		{
			root_tag_type: "feature_page",
			id: 5923249,
			name: "tasty_s_5th_birthday_recipe",
			display_name: "Tasty's 5th Birthday: Recipe",
			type: "feature_page",
		},
		{
			id: 6117480,
			name: "tasty_ewd_tips",
			display_name: "Tasty EWD Tips",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 6361700,
			name: "snickers",
			display_name: "Snickers",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			root_tag_type: "feature_page",
			id: 6361741,
			name: "peppermint_pattie",
			display_name: "Peppermint Pattie",
			type: "feature_page",
		},
		{
			root_tag_type: "business_tags",
			id: 6361775,
			name: "lil_brut",
			display_name: "Lil Brut",
			type: "business_tags",
		},
		{
			id: 6389771,
			name: "tasty_holiday_thanksgiving",
			display_name: "Tasty Holiday: Thanksgiving",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6543442,
			name: "nynm_money",
			display_name: "NYNM Money",
		},
		{
			name: "lunar_new_year",
			display_name: "Lunar New Year",
			type: "holidays",
			root_tag_type: "seasonal",
			id: 6573766,
		},
		{
			id: 6718870,
			name: "spring_drink",
			display_name: "Spring Drink",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			root_tag_type: "feature_page",
			id: 6718874,
			name: "spring_holiday",
			display_name: "Spring Holiday",
			type: "feature_page",
		},
		{
			id: 6854261,
			name: "cinco_de_mayo",
			display_name: "Cinco de Mayo",
			type: "holidays",
			root_tag_type: "seasonal",
		},
		{
			id: 6953016,
			name: "west_african",
			display_name: "West African",
			type: "african",
			root_tag_type: "cuisine",
		},
		{
			root_tag_type: "cuisine",
			id: 6953041,
			name: "haitian",
			display_name: "Haitian",
			type: "caribbean",
		},
		{
			type: "middle_eastern",
			root_tag_type: "cuisine",
			id: 6953042,
			name: "persian",
			display_name: "Persian",
		},
		{
			id: 6953051,
			name: "soul_food",
			display_name: "Soul Food",
			type: "north_american",
			root_tag_type: "cuisine",
		},
		{
			id: 6986104,
			name: "mccormick_ugc_one_pot_winners",
			display_name: "McCormick UGC One Pot Winners",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 6986105,
			name: "mccormick_ugc_one_pot_pasta",
			display_name: "McCormick UGC One Pot Pasta",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 6986106,
			name: "mccormick_ugc_one_pot_slow",
			display_name: "McCormick UGC One Pot Slow",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7336055,
			name: "shoppable_recipes_meal_prep",
			display_name: "Shoppable Recipes Meal Prep",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7559500,
			name: "shoppable_recipes_holiday_dinners",
			display_name: "Shoppable Recipes Holiday Dinners",
		},
		{
			name: "shoppable_recipes_seasonal_desserts",
			display_name: "Shoppable Recipes Seasonal Desserts",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7559501,
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7560082,
			name: "live_past_lives",
			display_name: "Live Past Lives",
		},
		{
			display_name: "Franks Spicy Bites",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7723148,
			name: "franks_spicy_bites",
		},
		{
			id: 7723149,
			name: "franks_nachos",
			display_name: "Franks Nachos",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 7783331,
			name: "butterfinger_winner",
			display_name: "Butterfinger Winner",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			root_tag_type: "feature_page",
			id: 8029893,
			name: "tasty_charcuterie_quizzes",
			display_name: "Tasty Charcuterie Quizzes",
			type: "feature_page",
		},
		{
			id: 8030030,
			name: "charcuterie_sweetchuterie",
			display_name: "Charcuterie Sweetchuterie",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8030032,
			name: "charcuterie_breakfast",
			display_name: "Charcuterie Breakfast",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8091744,
			name: "under_15_minutes",
			display_name: "Under 15 Minutes",
			type: "difficulty",
			root_tag_type: "difficulty",
		},
		{
			id: 8091916,
			name: "low_calorie",
			display_name: "Low-Calorie",
			type: "healthy",
			root_tag_type: "healthy",
		},
		{
			id: 8091919,
			name: "low_fat",
			display_name: "Low-Fat",
			type: "healthy",
			root_tag_type: "healthy",
		},
		{
			id: 8322952,
			name: "green",
			display_name: "Green",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8600870,
			name: "dole_sweet_treats",
			display_name: "Dole Sweet Treats",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8683061,
			name: "mccormick_holiday_drinks",
			display_name: "McCormick Holiday Drinks",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8719453,
			name: "dole_desserts",
			display_name: "Dole Desserts",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8860916,
			name: "kings_hawaiian_desserts",
			display_name: "Kings Hawaiian Desserts",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8874992,
			name: "nigeria_african_cuisine",
			display_name: "Nigeria African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8875010,
			name: "dr_african_cuisine",
			display_name: "DR African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8875011,
			name: "jamaica_african_cuisine",
			display_name: "Jamaica African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8875013,
			name: "pr_african_cuisine",
			display_name: "PR African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8875016,
			name: "east_africa_african_cuisine",
			display_name: "East Africa African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8875017,
			name: "south_africa_african_cuisine",
			display_name: "South Africa African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8907403,
			name: "incredible_egg_dinners",
			display_name: "Incredible Egg Dinners",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 9104329,
			name: "country_crock_veggies",
			display_name: "Country Crock Veggies",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			root_tag_type: "feature_page",
			id: 9164155,
			name: "ooni_other",
			display_name: "Ooni Other",
			type: "feature_page",
		},
		{
			display_name: "Seasonal",
			type: "seasonal",
			root_tag_type: "seasonal",
			id: 9295812,
			name: "seasonal",
		},
		{
			root_tag_type: "dietary",
			id: 9295814,
			name: "dietary",
			display_name: "Dietary",
			type: "dietary",
		},
		{
			id: 9295874,
			name: "european",
			display_name: "European",
			type: "cuisine",
			root_tag_type: "cuisine",
		},
		{
			display_name: "Southwestern",
			type: "north_american",
			root_tag_type: "cuisine",
			id: 9299355,
			name: "southwestern",
		},
		{
			name: "egg_breakfasts",
			display_name: "Egg Breakfasts",
			type: "breakfast",
			root_tag_type: "meal",
			id: 9299366,
		},
		{
			id: 9299370,
			name: "beverages",
			display_name: "Beverages",
			type: "breakfast",
			root_tag_type: "meal",
		},
		{
			type: "drinks",
			root_tag_type: "meal",
			id: 9299371,
			name: "cocktails",
			display_name: "Cocktails",
		},
		{
			display_name: "Pancakes",
			type: "sweet_breakfasts",
			root_tag_type: "meal",
			id: 9299397,
			name: "pancakes",
		},
		{
			id: 9299496,
			name: "wraps",
			display_name: "Wraps",
			type: "lunch",
			root_tag_type: "meal",
		},
		{
			display_name: "Pasta Salads",
			type: "salads",
			root_tag_type: "meal",
			id: 9299511,
			name: "pasta_salads",
		},
		{
			display_name: "Casseroles",
			type: "dinner",
			root_tag_type: "meal",
			id: 9299517,
			name: "casseroles",
		},
		{
			id: 9299519,
			name: "meat_loaf",
			display_name: "Meat Loaf",
			type: "dinner",
			root_tag_type: "meal",
		},
		{
			id: 9299520,
			name: "burgers",
			display_name: "Burgers",
			type: "dinner",
			root_tag_type: "meal",
		},
		{
			id: 9299521,
			name: "kabobs",
			display_name: "Kabobs",
			type: "dinner",
			root_tag_type: "meal",
		},
		{
			root_tag_type: "meal",
			id: 9299528,
			name: "stir_fry",
			display_name: "Stir Fry",
			type: "dinner",
		},
		{
			display_name: "Macaroni & Cheese",
			type: "pasta",
			root_tag_type: "meal",
			id: 9299623,
			name: "macaroni_cheese",
		},
		{
			id: 9299624,
			name: "seafood_pasta",
			display_name: "Seafood Pasta",
			type: "pasta",
			root_tag_type: "meal",
		},
		{
			id: 9299665,
			name: "cakes",
			display_name: "Cakes",
			type: "desserts",
			root_tag_type: "meal",
		},
		{
			id: 9299680,
			name: "pie_and_cobblers",
			display_name: "Pie and Cobblers",
			type: "desserts",
			root_tag_type: "meal",
		},
		{
			name: "brownies",
			display_name: "Brownies",
			type: "desserts",
			root_tag_type: "meal",
			id: 9299681,
		},
		{
			display_name: "Ice Cream",
			type: "desserts",
			root_tag_type: "meal",
			id: 9299683,
			name: "ice_cream",
		},
		{
			id: 9299685,
			name: "cheesecakes",
			display_name: "Cheesecakes",
			type: "cakes",
			root_tag_type: "meal",
		},
		{
			id: 9299688,
			name: "ice_cream_sandwiches",
			display_name: "Ice Cream Sandwiches",
			type: "ice_cream",
			root_tag_type: "meal",
		},
		{
			root_tag_type: "meal",
			id: 9299797,
			name: "rum",
			display_name: "Rum",
			type: "cocktails",
		},
		{
			display_name: "Juices",
			type: "drinks",
			root_tag_type: "meal",
			id: 9299833,
			name: "juices",
		},
		{
			display_name: "Kings Hawaiian Sliders",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 9345544,
			name: "kings_hawaiian_sliders",
		},
		{
			id: 9345546,
			name: "kings_hawaiian_perfect_sides",
			display_name: "Kings Hawaiian Perfect Sides",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 64446,
			name: "brazilian",
			display_name: "Brazilian",
			type: "central_south_american",
			root_tag_type: "cuisine",
		},
		{
			id: 64451,
			name: "mediterranean",
			display_name: "Mediterranean",
			type: "european",
			root_tag_type: "cuisine",
		},
		{
			type: "asian",
			root_tag_type: "cuisine",
			id: 64455,
			name: "korean",
			display_name: "Korean",
		},
		{
			id: 64456,
			name: "central_south_american",
			display_name: "Central & South American",
			type: "cuisine",
			root_tag_type: "cuisine",
		},
		{
			name: "healthy",
			display_name: "Healthy",
			type: "healthy",
			root_tag_type: "healthy",
			id: 64466,
		},
		{
			id: 64468,
			name: "vegan",
			display_name: "Vegan",
			type: "dietary",
			root_tag_type: "dietary",
		},
		{
			id: 64475,
			name: "4th_of_july",
			display_name: "4th of July",
			type: "holidays",
			root_tag_type: "seasonal",
		},
		{
			id: 64476,
			name: "halloween",
			display_name: "Halloween",
			type: "holidays",
			root_tag_type: "seasonal",
		},
		{
			type: "meal",
			root_tag_type: "meal",
			id: 64485,
			name: "desserts",
			display_name: "Desserts",
		},
		{
			id: 64491,
			name: "snacks",
			display_name: "Snacks",
			type: "meal",
			root_tag_type: "meal",
		},
		{
			name: "baking",
			display_name: "Baking",
			type: "appliance",
			root_tag_type: "appliance",
			id: 64492,
		},
		{
			type: "occasion",
			root_tag_type: "seasonal",
			id: 64503,
			name: "party",
			display_name: "Party",
		},
		{
			root_tag_type: "seasonal",
			id: 64509,
			name: "spring",
			display_name: "Spring",
			type: "seasonal",
		},
		{
			root_tag_type: "cuisine",
			id: 65410,
			name: "fusion",
			display_name: "Fusion",
			type: "cuisine",
		},
		{
			root_tag_type: "appliance",
			id: 65841,
			name: "dutch_oven",
			display_name: "Dutch Oven",
			type: "appliance",
		},
		{
			id: 65847,
			name: "slow_cooker",
			display_name: "Slow Cooker",
			type: "appliance",
			root_tag_type: "appliance",
		},
		{
			root_tag_type: "cooking_style",
			id: 65852,
			name: "mashup",
			display_name: "Mashup",
			type: "cooking_style",
		},
		{
			type: "equipment",
			root_tag_type: "equipment",
			id: 1247770,
			name: "colander",
			display_name: "Colander",
		},
		{
			id: 1247781,
			name: "peeler",
			display_name: "Peeler",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			display_name: "Spatula",
			type: "equipment",
			root_tag_type: "equipment",
			id: 1247788,
			name: "spatula",
		},
		{
			id: 1247791,
			name: "tupperware",
			display_name: "Tupperware",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			name: "whisk",
			display_name: "Whisk",
			type: "equipment",
			root_tag_type: "equipment",
			id: 1247793,
		},
		{
			display_name: "Baking Cups",
			type: "equipment",
			root_tag_type: "equipment",
			id: 1280499,
			name: "baking_cups",
		},
		{
			id: 1280503,
			name: "cutting_board",
			display_name: "Cutting Board",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			id: 1280511,
			name: "offset_spatula",
			display_name: "Offset Spatula",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			name: "one_top_app_seafood",
			display_name: "Seafood",
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 2651755,
		},
		{
			display_name: "Chop Champ",
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 3028912,
			name: "chop_champ",
		},
		{
			name: "holiday_cookie_recipe",
			display_name: "Holiday Cookie: Recipe",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 3527977,
		},
		{
			id: 3527978,
			name: "holiday_cookie_howto",
			display_name: "Holiday Cookie: How To",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 3527979,
			name: "holiday_cookie_hacks",
			display_name: "Holiday Cookie: Hacks",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 3801554,
			name: "caribbean",
			display_name: "Caribbean",
			type: "cuisine",
			root_tag_type: "cuisine",
		},
		{
			id: 3956653,
			name: "club_house_seasoned_pro",
			display_name: "Club House Seasoned Pro",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 4708980,
			name: "walmart_holiday_bundle",
			display_name: "Walmart Holiday Bundle",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			root_tag_type: "business_tags",
			id: 5143246,
			name: "mccormick_game_day",
			display_name: "McCormick Game Day",
			type: "business_tags",
		},
		{
			id: 6117477,
			name: "tasty_ewd_family",
			display_name: "Tasty EWD Family",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 6117479,
			name: "tasty_ewd_fifteen",
			display_name: "Tasty EWD Fifteen",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			root_tag_type: "feature_page",
			id: 6361701,
			name: "3_musketeers",
			display_name: "3 Musketeers",
			type: "feature_page",
		},
		{
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 6361812,
			name: "tasty_dinner_kits",
			display_name: "Tasty Dinner Kits",
		},
		{
			id: 6433722,
			name: "tasty_holiday_snacks",
			display_name: "Tasty Holiday: Snacks",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 6543465,
			name: "nynm_desserts",
			display_name: "NYNM Desserts",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6718864,
			name: "tips_basics",
			display_name: "Tips Basics",
		},
		{
			id: 6718869,
			name: "spring_eat",
			display_name: "Spring Eat",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 6742797,
			name: "passover",
			display_name: "Passover",
			type: "holidays",
			root_tag_type: "seasonal",
		},
		{
			name: "budget_shop",
			display_name: "Budget Shop",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6830251,
		},
		{
			id: 6931167,
			name: "air_fryer",
			display_name: "Air Fryer",
			type: "appliance",
			root_tag_type: "appliance",
		},
		{
			display_name: "Hawaiian",
			type: "north_american",
			root_tag_type: "cuisine",
			id: 6953012,
			name: "hawaiian",
		},
		{
			id: 6953046,
			name: "laotian",
			display_name: "Laotian",
			type: "asian",
			root_tag_type: "cuisine",
		},
		{
			root_tag_type: "cuisine",
			id: 6953050,
			name: "puerto_rican",
			display_name: "Puerto Rican",
			type: "caribbean",
		},
		{
			id: 7041320,
			name: "summer_eat",
			display_name: "Summer Eat",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7041321,
			name: "summer_drink",
			display_name: "Summer Drink",
		},
		{
			name: "summer_holiday",
			display_name: "Summer Holiday",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7041322,
		},
		{
			id: 7041323,
			name: "summer_sides",
			display_name: "Summer Sides",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			root_tag_type: "feature_page",
			id: 7041338,
			name: "fourth_drink",
			display_name: "Fourth Drink",
			type: "feature_page",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7436544,
			name: "uber_game_day_appetizers",
			display_name: "Uber Game Day Appetizers",
		},
		{
			root_tag_type: "feature_page",
			id: 7436547,
			name: "uber_game_day_sliders",
			display_name: "Uber Game Day Sliders",
			type: "feature_page",
		},
		{
			name: "charcuterie_inspiration",
			display_name: "Charcuterie Inspiration",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7987314,
		},
		{
			id: 7987315,
			name: "charcuterie_tips",
			display_name: "Charcuterie Tips",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 7987316,
			name: "charcuterie_recipes",
			display_name: "Charcuterie Recipes",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8104111,
			name: "mccormick_world_hearty",
			display_name: "McCormick World Hearty",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8104112,
			name: "mccormick_world_vegetarian",
			display_name: "McCormick World Vegetarian",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			root_tag_type: "feature_page",
			id: 8322950,
			name: "red",
			display_name: "Red",
			type: "feature_page",
		},
		{
			id: 8323092,
			name: "walmart_meal_planning",
			display_name: "Walmart Meal Planning",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 8757513,
			name: "cuisine",
			display_name: "Cuisine",
			type: "cuisine",
			root_tag_type: "cuisine",
		},
		{
			id: 8875009,
			name: "southernus_african_cuisine",
			display_name: "SouthernUS African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8875012,
			name: "brazil_african_cuisine",
			display_name: "Brazil African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8907402,
			name: "incredible_egg_lunches",
			display_name: "Incredible Egg Lunches",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			root_tag_type: "feature_page",
			id: 8907404,
			name: "incredible_egg_desserts",
			display_name: "Incredible Egg Desserts",
			type: "feature_page",
		},
		{
			id: 9295813,
			name: "meal",
			display_name: "Meal",
			type: "meal",
			root_tag_type: "meal",
		},
		{
			id: 9295816,
			name: "difficulty",
			display_name: "Difficulty",
			type: "difficulty",
			root_tag_type: "difficulty",
		},
		{
			id: 9299361,
			name: "new_years",
			display_name: "New Years",
			type: "holidays",
			root_tag_type: "seasonal",
		},
		{
			id: 9299367,
			name: "breakfast_sandwiches",
			display_name: "Breakfast Sandwiches",
			type: "breakfast",
			root_tag_type: "meal",
		},
		{
			id: 9299368,
			name: "smoothies_smoothie_bowls",
			display_name: "Smoothies & Smoothie Bowls",
			type: "breakfast",
			root_tag_type: "meal",
		},
		{
			root_tag_type: "meal",
			id: 9299369,
			name: "breads_pastries",
			display_name: "Breads & Pastries",
			type: "breakfast",
		},
		{
			type: "lunch",
			root_tag_type: "meal",
			id: 9299495,
			name: "salads",
			display_name: "Salads",
		},
		{
			name: "fruit_salads",
			display_name: "Fruit Salads",
			type: "salads",
			root_tag_type: "meal",
			id: 9299510,
		},
		{
			id: 9299622,
			name: "lasagna",
			display_name: "Lasagna",
			type: "pasta",
			root_tag_type: "meal",
		},
		{
			id: 9299682,
			name: "pastries",
			display_name: "Pastries",
			type: "desserts",
			root_tag_type: "meal",
		},
		{
			id: 9299684,
			name: "puddings",
			display_name: "Puddings",
			type: "desserts",
			root_tag_type: "meal",
		},
		{
			type: "ice_cream",
			root_tag_type: "meal",
			id: 9299687,
			name: "ice_cream_cakes",
			display_name: "Ice Cream Cakes",
		},
		{
			id: 9299834,
			name: "mocktails",
			display_name: "Mocktails",
			type: "drinks",
			root_tag_type: "meal",
		},
		{
			root_tag_type: "feature_page",
			id: 9345547,
			name: "kings_hawaiian_bbq_dessert",
			display_name: "Kings Hawaiian BBQ Dessert",
			type: "feature_page",
		},
		{
			id: 64450,
			name: "german",
			display_name: "German",
			type: "european",
			root_tag_type: "cuisine",
		},
		{
			id: 64457,
			name: "mexican",
			display_name: "Mexican",
			type: "north_american",
			root_tag_type: "cuisine",
		},
		{
			id: 64458,
			name: "middle_eastern",
			display_name: "Middle Eastern",
			type: "cuisine",
			root_tag_type: "cuisine",
		},
		{
			name: "dairy_free",
			display_name: "Dairy-Free",
			type: "dietary",
			root_tag_type: "dietary",
			id: 64463,
		},
		{
			type: "difficulty",
			root_tag_type: "difficulty",
			id: 64471,
			name: "easy",
			display_name: "Easy",
		},
		{
			display_name: "Under 30 Minutes",
			type: "difficulty",
			root_tag_type: "difficulty",
			id: 64472,
			name: "under_30_minutes",
		},
		{
			id: 64487,
			name: "drinks",
			display_name: "Drinks",
			type: "meal",
			root_tag_type: "meal",
		},
		{
			id: 64498,
			name: "steam",
			display_name: "Steam",
			type: "cooking_style",
			root_tag_type: "cooking_style",
		},
		{
			name: "happy_hour",
			display_name: "Happy Hour",
			type: "occasion",
			root_tag_type: "occasion",
			id: 64502,
		},
		{
			id: 64506,
			name: "tasty_cookbook",
			display_name: "Tasty Cookbook",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 64507,
			name: "tasty_junior_cookbook",
			display_name: "Tasty Junior Cookbook",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 64511,
			name: "winter",
			display_name: "Winter",
			type: "seasonal",
			root_tag_type: "seasonal",
		},
		{
			type: "appliance",
			root_tag_type: "appliance",
			id: 65848,
			name: "stove_top",
			display_name: "Stove Top",
		},
		{
			id: 65856,
			name: "stuffed",
			display_name: "Stuffed",
			type: "cooking_style",
			root_tag_type: "cooking_style",
		},
		{
			id: 65859,
			name: "pan_fry",
			display_name: "Pan Fry",
			type: "cooking_style",
			root_tag_type: "cooking_style",
		},
		{
			type: "equipment",
			root_tag_type: "equipment",
			id: 1247782,
			name: "pie_dish",
			display_name: "Pie Dish",
		},
		{
			type: "equipment",
			root_tag_type: "equipment",
			id: 1247784,
			name: "plastic_wrap",
			display_name: "Plastic Wrap",
		},
		{
			id: 1247786,
			name: "sauce_pan",
			display_name: "Sauce Pan",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			type: "equipment",
			root_tag_type: "equipment",
			id: 1247787,
			name: "saute_pan",
			display_name: "Saute Pan",
		},
		{
			id: 1247792,
			name: "wax_paper",
			display_name: "Wax Paper",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			type: "equipment",
			root_tag_type: "equipment",
			id: 1280500,
			name: "baking_pan",
			display_name: "Baking Pan",
		},
		{
			root_tag_type: "equipment",
			id: 1280508,
			name: "measuring_spoons",
			display_name: "Measuring Spoons",
			type: "equipment",
		},
		{
			name: "one_top_friendly",
			display_name: "One Top Friendly",
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 1691103,
		},
		{
			id: 2651753,
			name: "one_top_app_meat",
			display_name: "Meat",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 2651756,
			name: "one_top_app_veggies",
			display_name: "Veggies",
		},
		{
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 2651759,
			name: "one_top_app_grains",
			display_name: "Grains",
		},
		{
			name: "one_top_app_sauces",
			display_name: "Sauces",
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 2651760,
		},
		{
			display_name: "Ice Cream Social",
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 3801551,
			name: "ice_cream_social",
		},
		{
			id: 3801552,
			name: "pescatarian",
			display_name: "Pescatarian",
			type: "dietary",
			root_tag_type: "dietary",
		},
		{
			name: "black_history_month",
			display_name: "Black History Month",
			type: "holiday",
			root_tag_type: "holiday",
			id: 3802076,
		},
		{
			name: "mccormick_seasoned_pro",
			display_name: "McCormick Seasoned Pro",
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 3956651,
		},
		{
			id: 4767335,
			name: "pressure_cooker",
			display_name: "Pressure Cooker",
			type: "appliance",
			root_tag_type: "appliance",
		},
		{
			name: "qfp_baking",
			display_name: "Quarantine Cooking: Baking",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 5812431,
		},
		{
			display_name: "Oh So Rosé",
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 5923247,
			name: "oh_so_rose",
		},
		{
			id: 5949791,
			name: "light_bites",
			display_name: "Light Bites",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 5993378,
			name: "tasty_s_5th_birthday_sweet",
			display_name: "Tasty's 5th Birthday: Sweet",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			name: "tasty_s_5th_birthday_savory",
			display_name: "Tasty's 5th Birthday: Savory",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 5993379,
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6117478,
			name: "tasty_ewd_fall",
			display_name: "Tasty EWD Fall",
		},
		{
			id: 6207870,
			name: "walmart_plus_holiday_2020",
			display_name: "Walmart Plus Holiday 2020",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			display_name: "Almond Joy",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6361699,
			name: "almond_joy",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6477325,
			name: "frank_s_vegetarian_snacks",
			display_name: "Frank's Vegetarian Snacks",
		},
		{
			root_tag_type: "feature_page",
			id: 6543464,
			name: "nynm_protein",
			display_name: "NYNM Protein",
			type: "feature_page",
		},
		{
			root_tag_type: "feature_page",
			id: 6683352,
			name: "mc_breakfast_healthy",
			display_name: "MC Breakfast Healthy",
			type: "feature_page",
		},
		{
			display_name: "St. Patrick's Day",
			type: "holidays",
			root_tag_type: "seasonal",
			id: 6711300,
			name: "st_patrick_s_day",
		},
		{
			id: 6718866,
			name: "tips_pros",
			display_name: "Tips Pros",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			display_name: "Tips Culinary",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6718868,
			name: "tips_culinary",
		},
		{
			id: 6830252,
			name: "budget_four",
			display_name: "Budget Four",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 6953013,
			name: "ethiopian",
			display_name: "Ethiopian",
			type: "african",
			root_tag_type: "cuisine",
		},
		{
			id: 6953014,
			name: "kenyan",
			display_name: "Kenyan",
			type: "african",
			root_tag_type: "cuisine",
		},
		{
			name: "cuban",
			display_name: "Cuban",
			type: "caribbean",
			root_tag_type: "cuisine",
			id: 6953048,
		},
		{
			id: 7041337,
			name: "fourth_eat",
			display_name: "Fourth Eat",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 7336057,
			name: "shoppable_recipes_desserts",
			display_name: "Shoppable Recipes Desserts",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7510744,
			name: "thanksgiving_classics",
			display_name: "Thanksgiving Classics",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7560081,
			name: "live_jasmine_and_tucker",
			display_name: "Live Jasmine and Tucker",
		},
		{
			id: 7560083,
			name: "live_shop_all",
			display_name: "Live Shop All",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 7584483,
			name: "live_upcoming",
			display_name: "Live Upcoming",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 7608068,
			name: "shoppable_recipes_holiday_appetizers",
			display_name: "Shoppable Recipes Holiday Appetizers",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 7783334,
			name: "butterfinger_other_recipes",
			display_name: "Butterfinger Other Recipes",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			root_tag_type: "feature_page",
			id: 8030029,
			name: "charcuterie_dips",
			display_name: "Charcuterie Dips",
			type: "feature_page",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 8030031,
			name: "charcuterie_appetizers",
			display_name: "Charcuterie Appetizers",
		},
		{
			id: 8091917,
			name: "high_protein",
			display_name: "High-Protein",
			type: "healthy",
			root_tag_type: "healthy",
		},
		{
			id: 8091920,
			name: "high_fiber",
			display_name: "High-Fiber",
			type: "healthy",
			root_tag_type: "healthy",
		},
		{
			name: "mccormick_world_sides",
			display_name: "McCormick World Sides",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 8104110,
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 8104113,
			name: "mccormick_world_desserts",
			display_name: "McCormick World Desserts",
		},
		{
			display_name: "Blue",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 8322949,
			name: "blue",
		},
		{
			id: 8322951,
			name: "pink",
			display_name: "Pink",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8600867,
			name: "dole_morning_starters",
			display_name: "Dole Morning Starters",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8600869,
			name: "dole_crowd_pleasers",
			display_name: "Dole Crowd Pleasers",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			root_tag_type: "feature_page",
			id: 8719450,
			name: "dole_snacks",
			display_name: "Dole Snacks",
			type: "feature_page",
		},
		{
			name: "dole_hearty_meals",
			display_name: "Dole Hearty Meals",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 8719451,
		},
		{
			display_name: "Homemade Holiday",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 8747851,
			name: "homemade_holiday",
		},
		{
			id: 8860913,
			name: "kings_hawaiian_savory_wings",
			display_name: "Kings Hawaiian Savory Wings",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8860915,
			name: "kings_hawaiian_finger_foods",
			display_name: "Kings Hawaiian Finger Foods",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8875005,
			name: "kenya_african_cuisine",
			display_name: "Kenya African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 9164153,
			name: "ooni_classics",
			display_name: "Ooni Classics",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			name: "ooni_pizza",
			display_name: "Ooni Pizza",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 9164154,
		},
		{
			type: "cuisine",
			root_tag_type: "cuisine",
			id: 9295873,
			name: "asian",
			display_name: "Asian",
		},
		{
			root_tag_type: "seasonal",
			id: 9299130,
			name: "holidays",
			display_name: "Holidays",
			type: "seasonal",
		},
		{
			id: 9299354,
			name: "southern",
			display_name: "Southern",
			type: "north_american",
			root_tag_type: "cuisine",
		},
		{
			id: 9299360,
			name: "picnic",
			display_name: "Picnic",
			type: "occasion",
			root_tag_type: "seasonal",
		},
		{
			id: 9299362,
			name: "bread",
			display_name: "Bread",
			type: "baking",
			root_tag_type: "appliance",
		},
		{
			root_tag_type: "appliance",
			id: 9299363,
			name: "rolls",
			display_name: "Rolls",
			type: "baking",
		},
		{
			id: 9299364,
			name: "sweet_breakfasts",
			display_name: "Sweet Breakfasts",
			type: "breakfast",
			root_tag_type: "meal",
		},
		{
			name: "beef",
			display_name: "Beef",
			type: "dinner",
			root_tag_type: "meal",
			id: 9299515,
		},
		{
			root_tag_type: "meal",
			id: 9299518,
			name: "chilis",
			display_name: "Chilis",
			type: "dinner",
		},
		{
			root_tag_type: "meal",
			id: 9299649,
			name: "fish",
			display_name: "Fish",
			type: "seafood",
		},
		{
			type: "desserts",
			root_tag_type: "meal",
			id: 9299679,
			name: "cookies",
			display_name: "Cookies",
		},
		{
			display_name: "Tequila",
			type: "cocktails",
			root_tag_type: "meal",
			id: 9299796,
			name: "tequila",
		},
		{
			display_name: "Shakes",
			type: "drinks",
			root_tag_type: "meal",
			id: 9299832,
			name: "shakes",
		},
		{
			id: 9299957,
			name: "jewish",
			display_name: "Jewish",
			type: "cuisine",
			root_tag_type: "cuisine",
		},
		{
			id: 64447,
			name: "british",
			display_name: "British",
			type: "european",
			root_tag_type: "cuisine",
		},
		{
			id: 64448,
			name: "chinese",
			display_name: "Chinese",
			type: "asian",
			root_tag_type: "cuisine",
		},
		{
			name: "italian",
			display_name: "Italian",
			type: "european",
			root_tag_type: "cuisine",
			id: 64453,
		},
		{
			type: "holidays",
			root_tag_type: "seasonal",
			id: 64479,
			name: "thanksgiving",
			display_name: "Thanksgiving",
		},
		{
			root_tag_type: "meal",
			id: 64484,
			name: "brunch",
			display_name: "Brunch",
			type: "meal",
		},
		{
			name: "dinner",
			display_name: "Dinner",
			type: "meal",
			root_tag_type: "meal",
			id: 64486,
		},
		{
			id: 64489,
			name: "lunch",
			display_name: "Lunch",
			type: "meal",
			root_tag_type: "meal",
		},
		{
			id: 64490,
			name: "sides",
			display_name: "Sides",
			type: "meal",
			root_tag_type: "meal",
		},
		{
			id: 64494,
			name: "grill",
			display_name: "Grill",
			type: "cooking_style",
			root_tag_type: "cooking_style",
		},
		{
			id: 64508,
			name: "fall",
			display_name: "Fall",
			type: "seasonal",
			root_tag_type: "seasonal",
		},
		{
			name: "summer",
			display_name: "Summer",
			type: "seasonal",
			root_tag_type: "seasonal",
			id: 64510,
		},
		{
			display_name: "Blender",
			type: "appliance",
			root_tag_type: "appliance",
			id: 65838,
			name: "blender",
		},
		{
			id: 65839,
			name: "broiler",
			display_name: "Broiler",
			type: "appliance",
			root_tag_type: "appliance",
		},
		{
			id: 65842,
			name: "food_processor",
			display_name: "Food Processor",
			type: "appliance",
			root_tag_type: "appliance",
		},
		{
			id: 65843,
			name: "freezer_friendly",
			display_name: "Freezer Friendly",
			type: "appliance",
			root_tag_type: "appliance",
		},
		{
			id: 65845,
			name: "microwave",
			display_name: "Microwave",
			type: "appliance",
			root_tag_type: "appliance",
		},
		{
			root_tag_type: "equipment",
			id: 1247768,
			name: "cake_pan",
			display_name: "Cake Pan",
			type: "equipment",
		},
		{
			id: 1247769,
			name: "cheese_grater",
			display_name: "Cheese Grater",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			id: 1247772,
			name: "ice_cream_scoop",
			display_name: "Ice Cream Scoop",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			root_tag_type: "equipment",
			id: 1247774,
			name: "lollipop_sticks",
			display_name: "Lollipop Sticks",
			type: "equipment",
		},
		{
			type: "equipment",
			root_tag_type: "equipment",
			id: 1247775,
			name: "oven_mitts",
			display_name: "Oven Mitts",
		},
		{
			id: 1247776,
			name: "paper_bowls",
			display_name: "Paper Bowls",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			type: "equipment",
			root_tag_type: "equipment",
			id: 1247789,
			name: "strainer",
			display_name: "Strainer",
		},
		{
			id: 1247794,
			name: "wooden_spoon",
			display_name: "Wooden Spoon",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			id: 1247795,
			name: "zipper_freezer_bags",
			display_name: "Zipper Freezer Bags",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			id: 1280504,
			name: "fish_spatula",
			display_name: "Fish Spatula",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			type: "equipment",
			root_tag_type: "equipment",
			id: 1280506,
			name: "liquid_measuring_cup",
			display_name: "Liquid Measuring Cup",
		},
		{
			id: 1280507,
			name: "dry_measuring_cups",
			display_name: "Dry Measuring Cups",
			type: "equipment",
			root_tag_type: "equipment",
		},
		{
			id: 2651752,
			name: "one_top_app_main_feed",
			display_name: "Main Feed",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 2651757,
			name: "one_top_app_sides",
			display_name: "Sides",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			name: "one_top_app_dessert",
			display_name: "Dessert",
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 2651758,
		},
		{
			id: 2651761,
			name: "one_top_app_steak",
			display_name: "Steak",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 3802077,
			name: "asian_pacific_american_heritage_month",
			display_name: "Asian Pacific American Heritage Month",
			type: "holiday",
			root_tag_type: "holiday",
		},
		{
			id: 3802078,
			name: "pride_month",
			display_name: "Pride Month",
			type: "holiday",
			root_tag_type: "holiday",
		},
		{
			id: 4767341,
			name: "tastyjunior",
			display_name: "tastyjunior",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 5143247,
			name: "mccormick_easy_dinner",
			display_name: "McCormick Easy Dinner",
		},
		{
			id: 5812430,
			name: "qfp_recipes",
			display_name: "Quarantine Cooking: Recipe",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 5831533,
			name: "eko_video",
			display_name: "Eko Video",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 5923246,
			name: "beyond_red_blend",
			display_name: "Beyond Red Blend",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 5923248,
			name: "srsly_sauv_blanc",
			display_name: "Srsly Sauv Blanc",
		},
		{
			root_tag_type: "feature_page",
			id: 6117476,
			name: "tasty_ewd_healthy",
			display_name: "Tasty EWD Healthy",
			type: "feature_page",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6361740,
			name: "hershey_s",
			display_name: "Hershey's",
		},
		{
			id: 6361773,
			name: "deeply_blood_orange",
			display_name: "Deeply Blood Orange",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			id: 6361777,
			name: "perf_pinot_noir",
			display_name: "Perf Pinot Noir",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			display_name: "Raspberry Rosé",
			type: "business_tags",
			root_tag_type: "business_tags",
			id: 6361809,
			name: "raspberry_rose",
		},
		{
			id: 6361810,
			name: "sparkling_rose",
			display_name: "Sparkling Rosé",
			type: "business_tags",
			root_tag_type: "business_tags",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6389773,
			name: "tasty_holiday_hanukkah",
			display_name: "Tasty Holiday: Hanukkah",
		},
		{
			display_name: "Tasty Holiday: Festive Favorites",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6389775,
			name: "tasty_holiday_festive_favorites",
		},
		{
			display_name: "NYNM Expert",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6543462,
			name: "nynm_expert",
		},
		{
			display_name: "NYNM Meal Prep",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6543466,
			name: "nynm_meal_prep",
		},
		{
			id: 6718867,
			name: "tips_viral",
			display_name: "Tips Viral",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 6718875,
			name: "spring_sides",
			display_name: "Spring Sides",
		},
		{
			root_tag_type: "feature_page",
			id: 6718876,
			name: "spring_kitchen",
			display_name: "Spring Kitchen",
			type: "feature_page",
		},
		{
			id: 6830248,
			name: "budget_10",
			display_name: "Budget 10",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 6830249,
			name: "budget_plans",
			display_name: "Budget Plans",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			type: "holidays",
			root_tag_type: "seasonal",
			id: 6854262,
			name: "mothers_day",
			display_name: "Mother's Day",
		},
		{
			id: 6953008,
			name: "filipino",
			display_name: "Filipino",
			type: "asian",
			root_tag_type: "cuisine",
		},
		{
			display_name: "South African",
			type: "african",
			root_tag_type: "cuisine",
			id: 6953015,
			name: "south_african",
		},
		{
			id: 6953043,
			name: "lebanese",
			display_name: "Lebanese",
			type: "middle_eastern",
			root_tag_type: "cuisine",
		},
		{
			id: 6953044,
			name: "peruvian",
			display_name: "Peruvian",
			type: "central_south_american",
			root_tag_type: "cuisine",
		},
		{
			type: "caribbean",
			root_tag_type: "cuisine",
			id: 6953047,
			name: "dominican",
			display_name: "Dominican",
		},
		{
			name: "jamaican",
			display_name: "Jamaican",
			type: "caribbean",
			root_tag_type: "cuisine",
			id: 6953049,
		},
		{
			id: 6953052,
			name: "venezuelan",
			display_name: "Venezuelan",
			type: "central_south_american",
			root_tag_type: "cuisine",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7041336,
			name: "fourth_picks",
			display_name: "Fourth Picks",
		},
		{
			name: "fourth_sides",
			display_name: "Fourth Sides",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7041339,
		},
		{
			root_tag_type: "feature_page",
			id: 7041340,
			name: "fourth_desserts",
			display_name: "Fourth Desserts",
			type: "feature_page",
		},
		{
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7336056,
			name: "shoppable_recipes_family_dinner",
			display_name: "Shoppable Recipes Family Dinner",
		},
		{
			id: 7436545,
			name: "uber_game_day_dips",
			display_name: "Uber Game Day Dips",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			display_name: "Uber Game Day Ribs",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7436546,
			name: "uber_game_day_ribs",
		},
		{
			id: 7510745,
			name: "thanksgiving_sides",
			display_name: "Thanksgiving Sides",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			root_tag_type: "feature_page",
			id: 7510771,
			name: "thanksgiving_desserts",
			display_name: "Thanksgiving Desserts",
			type: "feature_page",
		},
		{
			name: "thanksgiving_sips",
			display_name: "Thanksgiving Sips",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7510772,
		},
		{
			id: 7559499,
			name: "shoppable_recipes_thanksgiving",
			display_name: "Shoppable Recipes Thanksgiving",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			name: "butterfinger_runner_up_bark",
			display_name: "Butterfinger Runner Up Bark",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 7783333,
		},
		{
			root_tag_type: "difficulty",
			id: 8091747,
			name: "under_45_minutes",
			display_name: "Under 45 Minutes",
			type: "difficulty",
		},
		{
			name: "under_1_hour",
			display_name: "Under 1 Hour",
			type: "difficulty",
			root_tag_type: "difficulty",
			id: 8091748,
		},
		{
			id: 8227134,
			name: "juneteenth",
			display_name: "Juneteenth",
			type: "holiday",
			root_tag_type: "holiday",
		},
		{
			name: "mccormick_holiday_appetizers",
			display_name: "McCormick Holiday Appetizers",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 8683062,
		},
		{
			id: 8683063,
			name: "mccormick_holiday_sides",
			display_name: "McCormick Holiday Sides",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8860912,
			name: "kings_hawaiian_roll_sliders",
			display_name: "Kings Hawaiian Roll Sliders",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8860914,
			name: "kings_hawaiian_delectable_dips",
			display_name: "Kings Hawaiian Delectable Dips",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8874993,
			name: "capeverde_african_cuisine",
			display_name: "CapeVerde African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8874994,
			name: "ghana_african_cuisine",
			display_name: "Ghana African Cuisine",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			id: 8907401,
			name: "incredible_egg_breakfasts",
			display_name: "Incredible Egg Breakfasts",
			type: "feature_page",
			root_tag_type: "feature_page",
		},
		{
			display_name: "Country Crock Desserts",
			type: "feature_page",
			root_tag_type: "feature_page",
			id: 9104326,
			name: "country_crock_desserts",
		},
		{
			display_name: "Cooking Style",
			type: "cooking_style",
			root_tag_type: "cooking_style",
			id: 9295810,
			name: "cooking_style",
		},
		{
			id: 9295811,
			name: "appliance",
			display_name: "Appliance",
			type: "appliance",
			root_tag_type: "appliance",
		},
		{
			display_name: "Waffles",
			type: "sweet_breakfasts",
			root_tag_type: "meal",
			id: 9299396,
			name: "waffles",
		},
		{
			name: "sandwiches",
			display_name: "Sandwiches",
			type: "lunch",
			root_tag_type: "meal",
			id: 9299494,
		},
		{
			root_tag_type: "meal",
			id: 9299497,
			name: "coleslaws",
			display_name: "Coleslaws",
			type: "salads",
		},
		{
			id: 9299512,
			name: "dressings",
			display_name: "Dressings",
			type: "salads",
			root_tag_type: "meal",
		},
		{
			display_name: "Chicken",
			type: "dinner",
			root_tag_type: "meal",
			id: 9299514,
			name: "chicken",
		},
		{
			root_tag_type: "meal",
			id: 9299516,
			name: "pork",
			display_name: "Pork",
			type: "dinner",
		},
		{
			root_tag_type: "meal",
			id: 9299523,
			name: "pizza",
			display_name: "Pizza",
			type: "dinner",
		},
		{
			id: 9299524,
			name: "pot_roast",
			display_name: "Pot Roast",
			type: "dinner",
			root_tag_type: "meal",
		},
		{
			name: "quiches",
			display_name: "Quiches",
			type: "dinner",
			root_tag_type: "meal",
			id: 9299525,
		},
		{
			id: 9299527,
			name: "stews",
			display_name: "Stews",
			type: "dinner",
			root_tag_type: "meal",
		},
		{
			id: 9299621,
			name: "baked_pasta",
			display_name: "Baked Pasta",
			type: "pasta",
			root_tag_type: "meal",
		},
		{
			id: 9299650,
			name: "shellfish",
			display_name: "Shellfish",
			type: "seafood",
			root_tag_type: "meal",
		},
		{
			name: "dips",
			display_name: "Dips",
			type: "appetizers",
			root_tag_type: "meal",
			id: 9299663,
		},
		{
			type: "appetizers",
			root_tag_type: "meal",
			id: 9299664,
			name: "sliders",
			display_name: "Sliders",
		},
		{
			type: "cakes",
			root_tag_type: "meal",
			id: 9299686,
			name: "cupcakes",
			display_name: "Cupcakes",
		},
		{
			root_tag_type: "meal",
			id: 9299793,
			name: "gin",
			display_name: "Gin",
			type: "cocktails",
		},
		{
			root_tag_type: "feature_page",
			id: 9345545,
			name: "kings_hawaiian_on_the_grill",
			display_name: "Kings Hawaiian On the Grill",
			type: "feature_page",
		},
	],
	prev: null,
	next: null,
};

export default tags;
